ZAIUS-12243: dynamic restrictions
ZaiusInc/resque-restriction pull request #1
Opened 2020-07-02 21:57 UTC by levilansing

- Allows for dynamic restrictions based on the arguments
- Allows for restrictions to change over time even against the same identifier key
- More robust concurrency, stops killed jobs/processes from restricting concurrency forever

Should be easier to review one commit at a time

2020-07-07 14:21 UTC, jasonaliyetti approved these changes
> Reviewed 4 of 4 files at r1, 3 of 3 files at r2, 4 of 4 files at r3, 5 of 5 files at r4.
> *[Reviewable](https://reviewable.io/reviews/zaiusinc/resque-restriction/1)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @derekharmel and @steelThread)



<!-- Sent from Reviewable.io -->

2020-07-08 14:48 UTC, derekharmel requested changes
> Reviewed 2 of 4 files at r1, 2 of 4 files at r3, 5 of 5 files at r4.
> *[Reviewable](https://reviewable.io/reviews/zaiusinc/resque-restriction/1)* status: all files reviewed, 4 unresolved discussions (waiting on @levilansing and @steelThread)

___
*[lib/resque/plugins/restriction.rb, line 80 at r4](https://reviewable.io/reviews/zaiusinc/resque-restriction/1#-MBig2XaDo85_wvVyTf-:-MBig2XaDo85_wvVyTf0:b-jemwiq) ([raw file](https://github.com/zaiusinc/resque-restriction/blob/039273ab021502cb8683398dede2cf81dc02e345/lib/resque/plugins/restriction.rb#L80)):*
> ```Ruby
>         concurrency_limiter.finish(concurrency_key) if concurrency_key
> 
>         # reincrement the keys if one of the periods triggers DontPerform so
> ```

"reincrement" isn't correct
___
*[lib/resque/plugins/restriction.rb, line 84 at r4](https://reviewable.io/reviews/zaiusinc/resque-restriction/1#-MBigDXg9Wq7_qrUbwzH:-MBigDXh1oGIBORfVDEb:b-fppqa7) ([raw file](https://github.com/zaiusinc/resque-restriction/blob/039273ab021502cb8683398dede2cf81dc02e345/lib/resque/plugins/restriction.rb#L84)):*
> ```Ruby
>         keys_incremented.each {|k| Resque.redis.incrby(k, -1) }
> 
>         Resque.push restriction_queue_name, :class => to_s, :args => args
> ```

Two style complaints (I know you didn't write this, rather only moved it): it's missing parens and it uses the old hash style syntax.
___
*[lib/resque/plugins/restriction.rb, line 141 at r4](https://reviewable.io/reviews/zaiusinc/resque-restriction/1#-MBigLL6AWJ9noSNznDl:-MBigLL6AWJ9noSNznDm:b-sgupjt) ([raw file](https://github.com/zaiusinc/resque-restriction/blob/039273ab021502cb8683398dede2cf81dc02e345/lib/resque/plugins/restriction.rb#L141)):*
> ```Ruby
>       rescue IsRestrictedError
>         # job is restricted, push to restriction queue
>         Resque.push restriction_queue_name, :class => to_s, :args => args
> ```

Same style complaint.
___
*[lib/resque/plugins/restriction/concurrency_limiter.rb, line 70 at r4](https://reviewable.io/reviews/zaiusinc/resque-restriction/1#-MBie8aP2qma0LEZBXmH:-MBie8aP2qma0LEZBXmI:bx1pjqi) ([raw file](https://github.com/zaiusinc/resque-restriction/blob/039273ab021502cb8683398dede2cf81dc02e345/lib/resque/plugins/restriction/concurrency_limiter.rb#L70)):*
> ```Ruby
>             loop do
>               sleep(CONCURRENT_HEARTBEAT)
>               @redis.pipelined do
> ```

This doesn't seem necessary.
___
*[spec/resque/plugins/restriction/concurrency_limiter_spec.rb, line 93 at r4](https://reviewable.io/reviews/zaiusinc/resque-restriction/1#-MBit16B7oEs-iw35-jX:-MBit16CApL-ubicj0rL:b-rbc56z) ([raw file](https://github.com/zaiusinc/resque-restriction/blob/039273ab021502cb8683398dede2cf81dc02e345/spec/resque/plugins/restriction/concurrency_limiter_spec.rb#L93)):*
> ```Ruby
>           # mock time so we can time-travel
>           mock_time = 1593719580
>           allow(Time).to receive(:now) { mock_time }
> ```

Doesn't `Time.now` return an instance of `Time`? I guess it doesn't break because your code always does `Time.now.to_i`, but it still seems a bit funky.


<!-- Sent from Reviewable.io -->

2020-07-08 15:15 UTC, levilansing reviewed
> *[Reviewable](https://reviewable.io/reviews/zaiusinc/resque-restriction/1)* status: 6 of 9 files reviewed, 4 unresolved discussions (waiting on @derekharmel, @jasonaliyetti, and @steelThread)

___
*[lib/resque/plugins/restriction.rb, line 80 at r4](https://reviewable.io/reviews/zaiusinc/resque-restriction/1#-MBig2XaDo85_wvVyTf-:-MBixUH84S-XKRp5LSVl:bryqalk) ([raw file](https://github.com/zaiusinc/resque-restriction/blob/039273ab021502cb8683398dede2cf81dc02e345/lib/resque/plugins/restriction.rb#L80)):*
<details><summary><i>Previously, derekharmel (Derek Harmel) wrote…</i></summary><blockquote>

"reincrement" isn't correct
</blockquote></details>

dang it. i thought i got all the old comments.
___
*[lib/resque/plugins/restriction.rb, line 84 at r4](https://reviewable.io/reviews/zaiusinc/resque-restriction/1#-MBigDXg9Wq7_qrUbwzH:-MBixY8PEorMDe67rPGh:b7aq17y) ([raw file](https://github.com/zaiusinc/resque-restriction/blob/039273ab021502cb8683398dede2cf81dc02e345/lib/resque/plugins/restriction.rb#L84)):*
<details><summary><i>Previously, derekharmel (Derek Harmel) wrote…</i></summary><blockquote>

Two style complaints (I know you didn't write this, rather only moved it): it's missing parens and it uses the old hash style syntax.
</blockquote></details>

I tried to generally maintain the existing style in existing files in case we decide to contribute back, but at this point my changes may be significant enough they won't want them anyway. I'll change it
___
*[lib/resque/plugins/restriction.rb, line 141 at r4](https://reviewable.io/reviews/zaiusinc/resque-restriction/1#-MBigLL6AWJ9noSNznDl:-MBiz3_aDLxQN1YoM_iF:bb7f2mf) ([raw file](https://github.com/zaiusinc/resque-restriction/blob/039273ab021502cb8683398dede2cf81dc02e345/lib/resque/plugins/restriction.rb#L141)):*
<details><summary><i>Previously, derekharmel (Derek Harmel) wrote…</i></summary><blockquote>

Same style complaint.
</blockquote></details>

done
___
*[lib/resque/plugins/restriction/concurrency_limiter.rb, line 70 at r4](https://reviewable.io/reviews/zaiusinc/resque-restriction/1#-MBie8aP2qma0LEZBXmH:-MBiye_Z8_pk_4GStfEA:b-m7d7on) ([raw file](https://github.com/zaiusinc/resque-restriction/blob/039273ab021502cb8683398dede2cf81dc02e345/lib/resque/plugins/restriction/concurrency_limiter.rb#L70)):*
<details><summary><i>Previously, derekharmel (Derek Harmel) wrote…</i></summary><blockquote>

This doesn't seem necessary.
</blockquote></details>

thanks, used to have a TTL call too until I learned zsets disappear when they're empty!
___
*[spec/resque/plugins/restriction/concurrency_limiter_spec.rb, line 93 at r4](https://reviewable.io/reviews/zaiusinc/resque-restriction/1#-MBit16B7oEs-iw35-jX:-MBiz8f01jO2lnT2jFza:bnurgpi) ([raw file](https://github.com/zaiusinc/resque-restriction/blob/039273ab021502cb8683398dede2cf81dc02e345/spec/resque/plugins/restriction/concurrency_limiter_spec.rb#L93)):*
<details><summary><i>Previously, derekharmel (Derek Harmel) wrote…</i></summary><blockquote>

Doesn't `Time.now` return an instance of `Time`? I guess it doesn't break because your code always does `Time.now.to_i`, but it still seems a bit funky.
</blockquote></details>

yeah, i was being lazy i think. fixed.


<!-- Sent from Reviewable.io -->

2020-07-08 15:32 UTC, derekharmel approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> but TBH I didn't really go through the concurrency limiting logic. I assume you referenced that article I Slacked you that one day and I'm going to further assume that logic is sound.

> Reviewed 3 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/zaiusinc/resque-restriction/1#-:-MBj2JVpAw7oGpKACies:b7xvl57)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @steelThread)

___
*[lib/resque/plugins/restriction/concurrency_limiter.rb, line 70 at r4](https://reviewable.io/reviews/zaiusinc/resque-restriction/1#-MBie8aP2qma0LEZBXmH:-MBj2AOQ6uYKliD_RcBC:bjtox5l) ([raw file](https://github.com/zaiusinc/resque-restriction/blob/039273ab021502cb8683398dede2cf81dc02e345/lib/resque/plugins/restriction/concurrency_limiter.rb#L70)):*
<details><summary><i>Previously, levilansing (Levi Lansing) wrote…</i></summary><blockquote>

thanks, used to have a TTL call too until I learned zsets disappear when they're empty!
</blockquote></details>

I believe that's true of most (all?) Redis keys.


<!-- Sent from Reviewable.io -->

2020-07-08 22:20 UTC, merged

2021-04-07 13:52 UTC, zorab47 commented
Any desire to share these improvements in the upstream project?